name: 'Create a tag'
description: 'Create a tag'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'tag'
  color: 'blue'

inputs:
  message:
    description: 'Message for the tag'
    required: false
    default: 'Automated version bump'
  prefix:
    description: 'String to be added before the version, for example if this parameter takes the value "v" the final tag will be "v8.0.0".'
    required: false
    default: ''
  version:
    description: 'Which version to increment. Allowed values are "major", "minor", "patch".'
    required: false
    default: 'patch'
  increment:
    description: 'Number to increment the version by. Default is set to 1'
    required: false
    default: '1'