name: 'Create a tag'
description: 'Create a tag'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'tag'
  color: 'blue'

inputs:
  increment_branch_tag:
    description: 'Whether tag versions should be relative to the current branch or globally in the repo (e.g. latest tag on branch is 2.1.0 and 4.0.0 on another branch)'
    required: false
    default: true
  message:
    description: 'Message for the tag'
    required: false
    default: 'Automated version bump'
  tag_prefix:
    description: 'String to be added before the tag, for example if this parameter takes the value "v" the final tag will be "v8.0.0".'
    required: false
    default: ''
